import userJWTDTO from '#Dto/user-jwt.dto.js';
import userLoginDTO from '#Dto/user-login.dto.js';
import userRegisterDTO from '#Dto/user-register.dto.js';
import userUnregisterDTO from '#Dto/user-unregister.dto.js';
import userUpdateDataDTO from '#Dto/user-update-data.dto.js';
import userUpdateEmailDTO from '#Dto/user-update-email.dto.js';
import userUpdatePasswordDTO from '#Dto/user-update-password.dto.js';
import { Router } from 'express';
const userRoutes = Router();
userRoutes.post('/register', userRegisterDTO);
userRoutes.post('/login', userLoginDTO);
userRoutes.get('/profile', userJWTDTO);
userRoutes.patch('/update-data', userJWTDTO, userUpdateDataDTO);
userRoutes.patch('/update-email', userJWTDTO, userUpdateEmailDTO);
userRoutes.patch('/update-password', userJWTDTO, userUpdatePasswordDTO);
userRoutes.delete('/unregister', userJWTDTO, userUnregisterDTO);
export default userRoutes;
